### ISSUE TITLE
Column width adjustment

### ISSUE THREAD

**Issue by LeninZapata** [raphaelgoetter/dirg#2]
Hello, for pictures in equal sizes it works, but what if the first column I need it bigger than the others. How could I do it? Could you add some variable that can make this useful in this way?

![image](https://user-images.githubusercontent.com/42600954/76402965-2d7f3180-6352-11ea-9142-41c6e4663103.png)

As you can see the first column becomes small but the next column does not adjust automatically, is it possible to adjust it automatically or through variables?

![image](https://user-images.githubusercontent.com/42600954/76403453-f1000580-6352-11ea-8663-6bfd19e8cc0c.png)

**Comment by raphaelgoetter** [comment]
Oh I see...

Is that what you want to build?

![image](https://user-images.githubusercontent.com/491029/76407879-59b7a400-638c-11ea-8fe6-d10d96547ef0.png)

I *could* add more and more variables for that, but usually it's not necessary to add these stuffs in a "superlight framework" since it can be added manually depending on projects needs.

What do you think?

**Comment by raphaelgoetter** [comment]
Well, actually it's a pretty simple add-on : 

```
:root {
  --grid-number: auto;
  --grid-gutter: 0;
  --grid-col: 1;
  --grid-row: 1;
  --grid-order: 0;
  --grid-col-start: auto;
  --grid-row-start: auto;
}

.DIRG {
  display: grid;
  grid-gap: var(--grid-gutter);
  grid-auto-flow: row dense;
}

@media (min-width: 576px) {
  .DIRG {
    grid-template-columns: repeat(var(--grid-number), 1fr);
  }
  .DIRG > * {
    grid-column: var(--grid-col-start) / span var(--grid-col, auto);
    grid-row: var(--grid-row-start) / span var(--grid-row, auto);
    order: var(--grid-order);
    min-width: 0;
  }
}
``` 

```
<div class="DIRG" style="--grid-number: 3; --grid-gutter: 1rem;">
  <div>1</div>
  <div>2</div>
  <div style="--grid-col: 2;">3</div>
  <div>4</div>
  <div style="--grid-row: 2;">5</div>
  <div>6</div>
  <div>7</div>
  <div style="--grid-col-start: 2; --grid-col: 2;">8</div>
</div>
```

**Comment by LeninZapata** [comment]
Thanks for the prompt response.
If the truth there looks better, with these changes I could make this combination quickly.
```html
<div class="DIRG" style="--grid-number: 10; --grid-gutter: 1rem;">
  <div style="--grid-col: 2;">1</div>
  <div style="--grid-col: 2;">2</div>
  <div style="--grid-col: 6;">3</div>
  <div style="--grid-col: 1; --grid-row: 2;">4</div>
  <div style="--grid-col: 5;">5</div>
  <div style="--grid-col: 3;">6</div>
  <div style="--grid-row: 2;">7</div>
  <div style="--grid-col-start:2; --grid-col: 8;">10</div>
</div>
```
**Result**
![image](https://user-images.githubusercontent.com/42600954/76436860-c0d25a00-6386-11ea-9764-800045e53265.png)

`---------------------------------------------------------------------`

Now how could I do so that in device tablet sizes I can manipulate the columns? that is to say that in tablet mode the result is this way with the same code in html but modify it on average in CSS

![image](https://user-images.githubusercontent.com/42600954/76437057-fd9e5100-6386-11ea-8c4d-f26476831e11.png)

Do you have an idea how to do it like this?

**Comment by raphaelgoetter** [comment]
There's no such "tablet" mode actually. Only a `(min-width: 576px)` trigger for Grid.

If you need many different templates, regarding on devices, DIRG won't be the best tool. You'll have to create your own CSS. 

For example : 

```css
@media (min-width: 576px) and (max-width :1023px) {
/* here goes a 2 column grid layout */
}
@media (min-width: 1024px)  {
/* here goes a X column grid layout */
}
```

**Comment by LeninZapata** [comment]
I know that.
I just wanted to know if you had an elegant solution with your script. I did it this way, I guess I should do it that way.

![image](https://user-images.githubusercontent.com/42600954/76441309-304b4800-638d-11ea-885c-1f4275038735.png)

**Comment by raphaelgoetter** [comment]
Yes, that's exactly how you could do it :)
